// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:hive/hive.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'dbcollection_model.freezed.dart';
part 'dbcollection_model.g.dart';

@freezed
class DbCollectionModel with _$DbCollectionModel {
  @HiveType(typeId: 0, adapterName: 'DbCollectionModelAdapter')
  const factory DbCollectionModel({
    @HiveField(0) required int id,
    @HiveField(1) required String title,
    @HiveField(2) required String description,
    @HiveField(3) required String image,
    @HiveField(4) required bool condition,
    @HiveField(5) required bool material,
    @HiveField(6) required bool country,
    @HiveField(7) required bool weight,
    @HiveField(8) required bool year,
  }) = _DbCollectionModel;

  factory DbCollectionModel.fromJson(Map<String, dynamic> json) =>
      _$DbCollectionModelFromJson(json);
}