// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:hive/hive.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'dbobject_model.freezed.dart';
part 'dbobject_model.g.dart';

@freezed
class DbObjectModel with _$DbObjectModel {
  @HiveType(typeId: 1, adapterName: 'DbObjectModelAdapter')
  const factory DbObjectModel({
    @HiveField(0) required int id,
    @HiveField(1) required int collectionid,
    @HiveField(2) required String articlename,
    @HiveField(3) required String description,
    @HiveField(4) required String image,
    @HiveField(5) required int condition,
    @HiveField(6) required double cost,
    @HiveField(7) required String material,
    @HiveField(8) required String country,
    @HiveField(9) required double weight,
    @HiveField(10) required DateTime obtaineddate,
    @HiveField(11) required bool favourite,
    @HiveField(12) required int releaseyear,
    @HiveField(13) required bool picenabled,
  }) = _DbObjectModel;

  factory DbObjectModel.fromJson(Map<String, dynamic> json) =>
      _$DbObjectModelFromJson(json);
}
